### PR TITLE
Tng 906 document dev mode

### PR DESCRIPTION
**Pull request by Dramaturco**
Added dev mode chapter. I also removed the dev mode chapter from the readme and added a link to it.

### CODE REVIEW

**Comment by dbarczewski** [comment]
Please leave the DevMode documentation in the Getting Started Guide so the developer doesn't have to jump back and forth while following the guide. 

The proper DevMode documentation should elaborate on this information. 
For example, there isn't documented what the `meta` or `[slot]: content` button is about.

**Review by dbarczewski — CHANGES_REQUESTED** [review]
Please leave the DevMode documentation in the Getting Started Guide so the developer doesn't have to jump back and forth while following the guide.

The proper DevMode documentation should elaborate on this information.
For example, there isn't documented what the `meta` or `[slot]: content` button is about.

**Comment by Dramaturco** [comment]
I was not aware that the devmode featured more than what's described in the readme and wanted to avoid duplicate text. If there is more to describe I will move the chapter back and go into more detail in the documentation.

**Review by dbarczewski — CHANGES_REQUESTED** [review]

**Review by dbarczewski — APPROVED** [review]
Looks fine to me now. 

@witthaus Could you please check the spelling?

**Pull request merged**
