### PR TITLE
TNG-965 Optimize dependencies for runtime environments

### PR DESCRIPTION
**Pull request by cfeddersen**
Goal: optimize dependencies to have a smaller footprint when running the PWA in production

* moved various dependencies from runtime to build time
* updated version of nuxt and other dependencies to get bugfixes and allow usage of nuxt-start

### CODE REVIEW

**Review by rrieger-espirit — CHANGES_REQUESTED** [review]
TNG-965 review so far:

Code Changes look good,

If you run "npm install" the package.json will be changed automatically (probably some dependencies new Versions or depricated modules)

After that i tried to run the "npm run lint" command where it says it cant find the modules 'Typescript'

What i did is a little quick fix by just running "npm install typescript" to check if all dependencies are available, seems like Typescript wasn't installed anymore.

The 'npm run Lint' now works a little further but another error occurs. Seems like we have a Parsing error since the Property Map is undefined in the InteractiveYoutubeVideo.tsx

Can you take a closer look on that?

**Comment by dbarczewski** [comment]
@rrieger-espirit 

Problem should be fixed, could you take a look at this and see if it is working properly on your machine?

**Comment by dbarczewski** [comment]
Please check if we can remove the @nuxtjs/dotenv dependency. See https://nuxtjs.org/blog/moving-from-nuxtjs-dotenv-to-runtime-config .

**Comment by rrieger-espirit** [comment]
added needed dependencies, this will work on any machine now. 
Also to remove dotenv, we need to make changes in the pwa and the nuxt-module.
This will need an own Ticket

**Pull request merged**
